In [1]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [2]:
embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

In [3]:
txt = "Hello World!"
txt_embedding = embeddings.embed_query(txt)

In [5]:
txt_embedding[:5]

[-0.03047031, 0.013959787, 0.023552177, -0.0658959, 0.005077092]

#### Finding similarity

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data.csv")
df

         Words
0     Elephant
1         Lion
2        Tiger
3          Dog
4      Cricket
5     Football
6       Tennis
7   Basketball
8        Apple
9       Orange
10      Banana
11      Grapes
12       Mango
13         Car
14        Bike
15         Bus
16       Train
17       Plane
18        Boat
19         Man

In [5]:
df['embeddings'] = df['Words'].apply(lambda x: embeddings.embed_query(x))
df.to_csv("words_embeddings.csv")

In [6]:
new_df = pd.read_csv("words_embeddings.csv")
new_df

    Unnamed: 0       Words                                         embeddings
0            0    Elephant  [-0.016539155, 0.01499971, 0.008784713, -0.046...
1            1        Lion  [-0.029194264, -0.008362333, 0.014222021, -0.0...
2            2       Tiger  [-0.0020874778, 0.003962656, -0.003618303, -0....
3            3         Dog  [-0.01504096, -0.014628819, 0.027180035, -0.05...
4            4     Cricket  [-0.004914075, 0.0044425246, 0.009979247, -0.0...
5            5    Football  [-0.014141238, 0.014424541, 0.03848089, -0.026...
6            6      Tennis  [-0.037738323, 0.012378344, -0.018752376, -0.0...
7            7  Basketball  [-0.01165769, -0.007918091, 0.00937423, -0.033...
8            8       Apple  [-0.014368307, 0.004756102, 0.031108672, -0.07...
9            9      Orange  [-0.012953188, -0.00041169688, 0.023733051, -0...
10          10      Banana  [-0.01421974, 0.00082445354, 0.00062447577, -0...
11          11      Grapes  [-0.012304055, 0.0103541985, 0.012110481, -0.0...
12          12       Mango  [-0.008865046, -0.018548569, 0.012956748, -0.0...
13          13         Car  [0.008721292, -0.0099598095, 0.014293275, -0.0...
14          14        Bike  [0.0011463272, 0.019052727, -0.0014854806, -0....
15          15         Bus  [-0.01971617, -0.004615959, 0.0018519594, -0.0...
16          16       Train  [-0.028893823, -0.011380679, 0.012781869, -0.0...
17          17       Plane  [-0.022960452, 0.0009839372, 0.028198233, -0.0...
18          18        Boat  [-0.019362975, -0.008951316, 0.0014527112, -0....
19          19         Man  [-0.0026250847, -0.012794464, 0.021118468, -0....

In [9]:
word = "Mango"
word_embedding = embeddings.embed_query(word)

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
df[f"{word}_similarity"] = df['embeddings'].apply(lambda x: cosine_similarity([x], [word_embedding])[0][0])
df

,Words,embeddings,Mango_similarity
0,Elephant,"[-0.016539155, 0.01499971, 0.008784713, -0.046...",0.651897
1,Lion,"[-0.029194264, -0.008362333, 0.014222021, -0.0...",0.628165
2,Tiger,"[-0.0020874778, 0.003962656, -0.003618303, -0....",0.663362
3,Dog,"[-0.01504096, -0.014628819, 0.027180035, -0.05...",0.630826
4,Cricket,"[-0.004914075, 0.0044425246, 0.009979247, -0.0...",0.620744
5,Football,"[-0.014141238, 0.014424541, 0.03848089, -0.026...",0.577466
6,Tennis,"[-0.037738323, 0.012378344, -0.018752376, -0.0...",0.615857
7,Basketball,"[-0.01165769, -0.007918091, 0.00937423, -0.033...",0.575189
8,Apple,"[-0.014368307, 0.004756102, 0.031108672, -0.07...",0.689117
9,Orange,"[-0.012953188, -0.00041169688, 0.023733051, -0...",0.694164
10,Banana,"[-0.01421974, 0.00082445354, 0.00062447577, -0...",0.743739
11,Grapes,"[-0.012304055, 0.0103541985, 0.012110481, -0.0...",0.666780
12,Mango,"[-0.008865046, -0.018548569, 0.012956748, -0.0...",1.000000
13,Car,"[0.008721292, -0.0099598095, 0.014293275, -0.0...",0.625051
14,Bike,"[0.0011463272, 0.019052727, -0.0014854806, -0....",0.606131
15,Bus,"[-0.01971617, -0.004615959, 0.0018519594, -0.0...",0.611966
16,Train,"[-0.028893823, -0.011380679, 0.012781869, -0.0...",0.601873
17,Plane,"[-0.022960452, 0.0009839372, 0.028198233, -0.0...",0.632123
18,Boat,"[-0.019362975, -0.008951316, 0.0014527112, -0....",0.620045
19,Man,"[-0.0026250847, -0.012794464, 0.021118468, -0....",0.659828